//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

#![allow(dead_code, unused_imports)]

use doido::model::sea_orm as sea_orm;
use doido::model::sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    pub conversation_id: i64,
    pub user_id: i64,
    pub message_type: String,
    pub created_at: DateTimeUtc,
    #[sea_orm(column_type = "Binary(1)", nullable)]
    pub image_data: Option<Vec<u8>>,
    pub image_content_type: Option<String>,
    pub image_filename: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
