// Tests for the Conversation model. Generated by `doido generate model`.
//
// TODO: write tests for Conversation. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn conversation_model_todo() {
    // TODO: replace with real assertions for the Conversation model.
}
