// Tests for ConversationChannel. Generated by `doido generate channel`.
//
// TODO: write tests for ConversationChannel.

#[test]
fn conversation_channel_todo() {
    // TODO: assert the channel's behavior.
}
