// Tests for the Message model. Generated by `doido generate model`.
//
// TODO: write tests for Message. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn message_model_todo() {
    // TODO: replace with real assertions for the Message model.
}
