//! The job-type registry: the missing link between a reserved [`JobPayload`] and
//! the code that runs it (Rails' Active Job "class name → `perform`" lookup).
//!
//! The `#[job]` macro stamps each payload with its job name (see
//! [`JobPayload::with_name`]) and registers a handler that deserializes the
//! payload and calls the job's function. Registration is link-time via the
//! [`inventory`] crate, so simply defining a `#[job]` makes it runnable — the
//! worker builds the registry with [`JobRegistry::from_inventory`] and routes
//! each reserved job to its handler.

use crate::context::JobContext;
use crate::queue::JobPayload;
use doido_core::{anyhow::anyhow, Result};
use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

/// A boxed, `Send` future returned by a job handler.
pub type HandlerFuture = Pin<Box<dyn Future<Output = Result<()>> + Send>>;

/// A job handler: deserializes a payload and runs the job body. Generated by the
/// `#[job]` macro; a plain `fn` pointer so it can live in an `inventory` item.
pub type HandlerFn = fn(JobPayload, Arc<JobContext>) -> HandlerFuture;

/// One `#[job]`'s registration, submitted at link time via `inventory::submit!`.
pub struct JobRegistration {
    /// The job's name — matches [`JobPayload::job_name`].
    pub name: &'static str,
    /// The handler that runs a payload for this job.
    pub handler: HandlerFn,
}

inventory::collect!(JobRegistration);

/// Maps a job name to its handler. Built once at worker boot.
#[derive(Default, Clone)]
pub struct JobRegistry {
    handlers: HashMap<&'static str, HandlerFn>,
}

impl JobRegistry {
    /// An empty registry (tests may `register` handlers directly).
    pub fn new() -> Self {
        Self::default()
    }

    /// Build the registry from every `#[job]` linked into the binary.
    pub fn from_inventory() -> Self {
        let mut registry = Self::new();
        for reg in inventory::iter::<JobRegistration> {
            registry.handlers.insert(reg.name, reg.handler);
        }
        registry
    }

    /// Register a handler explicitly (used by tests and for programmatic jobs).
    pub fn register(&mut self, name: &'static str, handler: HandlerFn) -> &mut Self {
        self.handlers.insert(name, handler);
        self
    }

    /// The names of all registered jobs (for `doido jobs`/diagnostics).
    pub fn names(&self) -> Vec<&'static str> {
        self.handlers.keys().copied().collect()
    }

    /// Run `job` on its registered handler. Returns `Err` for an unknown job
    /// name so the engine applies its retry/dead-letter policy instead of
    /// silently dropping work with no handler.
    pub async fn dispatch(&self, job: JobPayload, ctx: Arc<JobContext>) -> Result<()> {
        match self.handlers.get(job.job_name.as_str()) {
            Some(handler) => handler(job, ctx).await,
            None => Err(anyhow!(
                "no handler registered for job `{}` (is its `#[job]` crate linked?)",
                job.job_name
            )),
        }
    }
}
