// Tests for the ConversationParticipant model. Generated by `doido generate model`.
//
// TODO: write tests for ConversationParticipant. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn conversation_participant_model_todo() {
    // TODO: replace with real assertions for the ConversationParticipant model.
}
