CREATE TABLE public.bank_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    bank_id bigint NOT NULL,
    agency character varying NOT NULL,
    account_number character varying NOT NULL,
    cpf_cnpj character varying NOT NULL,
    account_type character varying DEFAULT 'corrente'::character varying NOT NULL
);
ALTER TABLE public.bank_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.bank_statement_imports (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    bank_account_id bigint NOT NULL,
    company_id bigint NOT NULL,
    source character varying NOT NULL,
    statement_type character varying NOT NULL,
    original_filename character varying NOT NULL,
    compressed_data bytea NOT NULL,
    file_checksum character varying NOT NULL,
    byte_size bigint NOT NULL,
    transactions_imported integer DEFAULT 0 NOT NULL,
    status character varying DEFAULT 'completed'::character varying NOT NULL,
    error_message text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
ALTER TABLE public.bank_statement_imports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_statement_imports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.banks (
    id bigint NOT NULL,
    name character varying NOT NULL,
    code character varying NOT NULL,
    country_id bigint NOT NULL
);
ALTER TABLE public.banks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.categories (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    name character varying NOT NULL
);
ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.companies (
    id bigint NOT NULL,
    name character varying NOT NULL,
    slug character varying NOT NULL
);
ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.counterparties (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    name character varying NOT NULL
);
ALTER TABLE public.counterparties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.counterparties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.countries (
    id bigint NOT NULL,
    name character varying NOT NULL,
    code character varying NOT NULL
);
ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.doido_jobs (
    id text NOT NULL,
    queue text NOT NULL,
    status text NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    run_at bigint NOT NULL,
    locked_at bigint,
    data text NOT NULL
);
CREATE TABLE public.memberships (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    company_id bigint NOT NULL,
    salary numeric,
    role character varying DEFAULT 'member'::character varying NOT NULL
);
ALTER TABLE public.memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.seaql_migrations (
    version character varying NOT NULL,
    applied_at bigint NOT NULL
);
CREATE TABLE public.storage_attachments (
    id bigint NOT NULL,
    name character varying NOT NULL,
    record_type character varying NOT NULL,
    record_id character varying NOT NULL,
    blob_key character varying NOT NULL,
    created_at timestamp without time zone NOT NULL
);
ALTER TABLE public.storage_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.storage_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.storage_blobs (
    id bigint NOT NULL,
    key character varying NOT NULL,
    filename character varying NOT NULL,
    content_type character varying,
    metadata text,
    service_name character varying NOT NULL,
    byte_size bigint NOT NULL,
    checksum character varying,
    created_at timestamp without time zone NOT NULL
);
ALTER TABLE public.storage_blobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.storage_blobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.storage_variant_records (
    id bigint NOT NULL,
    blob_key character varying NOT NULL,
    variation_digest character varying NOT NULL
);
ALTER TABLE public.storage_variant_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.storage_variant_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.transactions (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    bank_account_id bigint NOT NULL,
    category_id bigint NOT NULL,
    occurred_at timestamp without time zone NOT NULL,
    amount numeric NOT NULL,
    operation character varying DEFAULT 'SAIDA'::character varying NOT NULL,
    movement_type character varying DEFAULT 'balance'::character varying NOT NULL,
    counterparty_id bigint
);
ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying NOT NULL,
    password_digest character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_statement_imports
    ADD CONSTRAINT bank_statement_imports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.banks
    ADD CONSTRAINT banks_code_key UNIQUE (code);
ALTER TABLE ONLY public.banks
    ADD CONSTRAINT banks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_slug_key UNIQUE (slug);
ALTER TABLE ONLY public.counterparties
    ADD CONSTRAINT counterparties_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_code_key UNIQUE (code);
ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.doido_jobs
    ADD CONSTRAINT doido_jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.seaql_migrations
    ADD CONSTRAINT seaql_migrations_pkey PRIMARY KEY (version);
ALTER TABLE ONLY public.storage_attachments
    ADD CONSTRAINT storage_attachments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.storage_blobs
    ADD CONSTRAINT storage_blobs_key_key UNIQUE (key);
ALTER TABLE ONLY public.storage_blobs
    ADD CONSTRAINT storage_blobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.storage_variant_records
    ADD CONSTRAINT storage_variant_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX idx_bank_statement_imports_checksum_account ON public.bank_statement_imports USING btree (bank_account_id, file_checksum);
CREATE INDEX idx_doido_jobs_reserve ON public.doido_jobs USING btree (queue, status, run_at);
CREATE INDEX idx_storage_attachments_record_type_record_id_name ON public.storage_attachments USING btree (record_type, record_id, name);
CREATE INDEX idx_storage_variant_records_blob_key_variation_digest ON public.storage_variant_records USING btree (blob_key, variation_digest);
ALTER TABLE ONLY public.banks
    ADD CONSTRAINT fk_banks_country_id FOREIGN KEY (country_id) REFERENCES public.countries(id);
