//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

#![allow(dead_code, unused_imports)]

use doido::model::sea_orm as sea_orm;
use doido::model::sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::models::enums::{ImportSource, ImportStatementType, ImportStatus};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize,
)]
#[sea_orm(table_name = "bank_statement_imports")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    #[sea_orm(unique_key = "idx_bank_statement_imports_checksum_account")]
    pub bank_account_id: i64,
    pub company_id: i64,
    pub source: ImportSource,
    pub statement_type: ImportStatementType,
    pub original_filename: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub compressed_data: Vec<u8>,
    #[sea_orm(unique_key = "idx_bank_statement_imports_checksum_account")]
    pub file_checksum: String,
    pub byte_size: i64,
    pub transactions_imported: i32,
    pub status: ImportStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
