//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

#![allow(dead_code, unused_imports)]

use doido::model::sea_orm as sea_orm;
use doido::model::sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize,
)]
#[sea_orm(table_name = "storage_attachments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub record_type: String,
    pub record_id: String,
    pub blob_key: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
