use crate::generator::{GeneratedFile, Generator};
use crate::generators::{to_pascal, to_snake, to_table_name};
use doido_core::{anyhow::anyhow, Result};

/// Fallback `app/generators/mod.rs` when the app doesn't have one on disk yet.
const GEN_MOD_BASE: &str = include_str!("../../templates/new/app/generators/mod.rs");
const GEN_MOD_PATH: &str = "app/generators/mod.rs";
/// Fallback `src/main.rs` (channels placeholder stripped) for the same reason.
const MAIN_BASE: &str = include_str!("../../templates/new/src/main.rs");
const MAIN_PATH: &str = "src/main.rs";

/// Marker both the module registry and the `Doido` builder carry; registrations
/// are injected just above it.
const MARKER: &str = "@generated-generators";

/// `doido generate generator <name>` — scaffolds an app-owned Rust generator
/// under `app/generators/<snake>.rs`, registers it in `app/generators/mod.rs`,
/// and wires `.register_generator(...)` into the `Doido` builder in
/// `src/main.rs`. After a rebuild, `cargo doido generate <snake> <Name>`
/// dispatches it alongside the framework built-ins.
pub struct GeneratorGenerator;

impl Generator for GeneratorGenerator {
    fn name(&self) -> &str {
        "generator"
    }

    fn generate(&self, args: &[&str]) -> Result<Vec<GeneratedFile>> {
        let name = args
            .first()
            .copied()
            .ok_or_else(|| anyhow!("generator generator requires a name argument"))?;
        let snake = to_snake(name);
        let pascal = to_pascal(name);
        let plural = to_table_name(name);
        let struct_name = format!("{pascal}Generator");

        let mod_existing =
            std::fs::read_to_string(GEN_MOD_PATH).unwrap_or_else(|_| GEN_MOD_BASE.to_string());
        let main_existing = std::fs::read_to_string(MAIN_PATH).unwrap_or_else(|_| main_base());

        Ok(vec![
            GeneratedFile {
                path: format!("app/generators/{snake}.rs"),
                content: generator_source(&snake, &pascal, &plural),
            },
            GeneratedFile {
                path: GEN_MOD_PATH.to_string(),
                content: register_in_mod(&mod_existing, &snake, &struct_name),
            },
            GeneratedFile {
                path: MAIN_PATH.to_string(),
                content: register_in_main(&main_existing, &struct_name),
            },
        ])
    }
}

/// The `src/main.rs` template with the channels placeholder stripped, used only
/// when the app has no `src/main.rs` on disk (a real app always does).
fn main_base() -> String {
    MAIN_BASE.replace("{doido_channels_module}", "")
}

/// The scaffolded generator: a real `doido::Generator` the app compiles in.
fn generator_source(snake: &str, pascal: &str, plural: &str) -> String {
    format!(
        r#"use doido::{{GeneratedFile, Generator}};

/// App-owned code generator, registered on the `Doido` builder in `src/main.rs`.
/// Run it with `cargo doido generate {snake} <Name>`.
pub struct {pascal}Generator;

impl Generator for {pascal}Generator {{
    fn name(&self) -> &str {{
        "{snake}"
    }}

    fn generate(&self, args: &[&str]) -> doido::core::Result<Vec<GeneratedFile>> {{
        // `name` is the argument passed on the CLI, e.g. `generate {snake} Post`.
        let name = args.first().copied().unwrap_or("Example");

        // TODO: customise the files this generator emits.
        Ok(vec![GeneratedFile {{
            path: format!("app/{plural}/{{}}.rs", name.to_lowercase()),
            content: format!("// {{name}} — generated by the `{snake}` generator\n"),
        }}])
    }}
}}
"#
    )
}

/// Add `mod <snake>;` + `pub use <snake>::<Struct>;` to `app/generators/mod.rs`,
/// just above the marker. Idempotent on the module declaration.
fn register_in_mod(existing: &str, snake: &str, struct_name: &str) -> String {
    let decl = format!("mod {snake};");
    if existing.lines().any(|l| l.trim() == decl) {
        return existing.to_string();
    }
    let use_line = format!("pub use {snake}::{struct_name};");
    let mut lines: Vec<String> = existing.lines().map(String::from).collect();
    match lines.iter().position(|l| l.contains(MARKER)) {
        Some(i) => {
            lines.insert(i, use_line);
            lines.insert(i, decl);
        }
        None => {
            lines.push(decl);
            lines.push(use_line);
        }
    }
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// Inject `.register_generator(Box::new(generators::<Struct>))` into the `Doido`
/// builder in `src/main.rs`, just above the marker and matching its indentation.
/// Idempotent; leaves `main.rs` untouched when the marker is absent.
fn register_in_main(existing: &str, struct_name: &str) -> String {
    let call = format!(".register_generator(Box::new(generators::{struct_name}))");
    if existing.lines().any(|l| l.trim() == call) {
        return existing.to_string();
    }
    let mut lines: Vec<String> = existing.lines().map(String::from).collect();
    match lines.iter().position(|l| l.contains(MARKER)) {
        Some(i) => {
            let indent: String = lines[i].chars().take_while(|c| c.is_whitespace()).collect();
            lines.insert(i, format!("{indent}{call}"));
        }
        None => return existing.to_string(),
    }
    let mut out = lines.join("\n");
    out.push('\n');
    out
}
