// Tests for the add_description_to_transactions migration. Generated by `doido generate migration`.
//
// TODO: write tests for the add_description_to_transactions migration (e.g. apply it against an
// in-memory database and assert the resulting schema).

#[test]
fn add_description_to_transactions_migration_todo() {
    // TODO: assert the migration's behavior.
}
