// Tests for the Bank model. Generated by `doido generate model`.
//
// TODO: write tests for Bank. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn bank_model_todo() {
    // TODO: replace with real assertions for the Bank model.
}
