// Tests for the BankAccount model. Generated by `doido generate model`.
//
// TODO: write tests for BankAccount. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn bank_account_model_todo() {
    // TODO: replace with real assertions for the BankAccount model.
}
