// Tests for the Category model. Generated by `doido generate model`.
//
// TODO: write tests for Category. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn category_model_todo() {
    // TODO: replace with real assertions for the Category model.
}
