// Tests for the Counterparty model. Generated by `doido generate model`.
//
// TODO: write tests for Counterparty. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn counterparty_model_todo() {
    // TODO: replace with real assertions for the Counterparty model.
}
