// Tests for the Membership model. Generated by `doido generate model`.
//
// TODO: write tests for Membership. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn membership_model_todo() {
    // TODO: replace with real assertions for the Membership model.
}
