// Tests for the Transaction model. Generated by `doido generate model`.
//
// TODO: write tests for Transaction. A model unit test typically exercises
// validations, scopes, and associations against an in-memory database.

#[test]
fn transaction_model_todo() {
    // TODO: replace with real assertions for the Transaction model.
}
